### ISSUE TITLE
[FEATURE] 시작 페이지 UI

### ISSUE THREAD

**Issue by SJ0826** [SJ0826/random-message-project#3]
## 📑 Todo
- [x]  프로젝트 간단한 설명이 들어갑니다.
- [x] 받아온 메세지 리스트를 렌더링 합니다.
- [x]  메세지 보내기 버튼을 눌러 메세지 페이지로 이동합니다.
- [x] firebase에서 데이터 가져오기
