### ISSUE TITLE
[FEATURE/send-message] 메세지 보내기

### ISSUE THREAD

**Issue by SJ0826** [SJ0826/random-message-project#7]
## 📑 Todo
* [x] 메시지 창에서 이름을 입력한다.
* [x] 메세지를 보내면 하나의 메세지를 받는다.
* [x] 반응형 디자인 추가
